[package]
name = "phobos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.37.0"
ash-window = "0.12.0"
raw-window-handle = "0.5.0"
gpu-allocator = "0.20.0"
smallvec = "1.10.0"
derivative = "2.2.0"
winit = { version = "0.27.5", optional = true }