[package]
name = "phobos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = { version = "0.37.0", features = ["debug"] }
ash-window = "0.12.0"
raw-window-handle = "0.5.0"
gpu-allocator = "0.20.0"
smallvec = "1.10.0"
derivative = "2.2.0"
futures = "0.3.25"
petgraph = "0.6.2"
layout-rs = "0.1.1"
winit = { version = "0.27.5", optional = true }
bitflags = "1.3.2"

[features]
default = ["winit"]
# Logs creation and destruction of all Vulkan objects. Useful for debugging.
log-objects = []
